### ISSUE TITLE
7703 Segmentation fault. 

### ISSUE THREAD

**Issue by raul1968** [ktaebum/AttentionedDeepPaint#11]
Could this be a lack of permission in the Dir? The dataset was corrupted but I was able to unzip most of it. 

train.sh: line 3:  7703 Segmentation fault      (core dumped) python train.py --verbose --save-every 5 --model deepunet --sample 4 --no-mse --num-epochs 15 --print-every 300 --train

**Comment by raul1968** [comment]
Downgraded  Pytorch to  0.4.1.   Fixed

**Comment by ktaebum** [comment]
thank you for report! I will fix it to compatible with torch 1.0

**Comment by ExplorerLGD** [comment]
The dataset was corrupted,is that alright?

**Comment by ExplorerLGD** [comment]
The dataset was corrupted...
Is there a way to fix it?

**Comment by ktaebum** [comment]
@ExplorerLGD I will also check about it.

**Comment by ktaebum** [comment]
@ExplorerLGD could you explain how datasets are corrupted? It does not raise problem to me..

**Comment by ExplorerLGD** [comment]
@ktaebum This problem is solved by unzip with 7-zip,I don't know what's going on.

https://www.kaggle.com/c/noaa-fisheries-steller-sea-lion-population-count/discussion/30930

**Comment by raul1968** [comment]
> @ExplorerLGD could you explain how datasets are corrupted? It does not raise problem to me..

You have to do an unzip (filename.zip) at the command line. Then you won't get an error.

**Comment by ExplorerLGD** [comment]
@raul1968  thanks for your tip！

**Comment by ktaebum** [comment]
@raul1968  current version does not crash in torch 1.0. I will close this issue
