### ISSUE TITLE
Why are my results rough？

### ISSUE THREAD

**Issue by tree-branch** [ktaebum/AttentionedDeepPaint#15]
![image](https://user-images.githubusercontent.com/24783484/55853577-4d333600-5b94-11e9-813b-fb1a2b4698e8.png)
Your effect is really amazing.
I changed the size of the image to 256.
Is this an intermediate outcome from your training？

**Comment by ktaebum** [comment]
Sorry for late reply :(
Hmm actually I did not test for 256 x 256 image.
However, I think the model structure should be slightly modified for different image resolution :(
