### ISSUE TITLE
May you share some pre-trained  models?

### ISSUE THREAD

**Issue by AnonymousPomp** [ktaebum/AttentionedDeepPaint#18]
Since not all people have a decent GPU to train the network (I only have a laptop), I think it's a good idea to share a pre-trained network.
Preferably the one used to make the images on the README.md

**Comment by ktaebum** [comment]
Sorry for late reply
Actually, you can use single pretrained model in release page :)

**Comment by AnonymousPomp** [comment]
Oh there's a release page!
didn't notice that.
thank you!!
